apiVersion: v1
kind: Service
metadata:
  name: mosbot-api
  namespace: mosbot
  labels:
    app: mosbot-api
spec:
  selector:
    app: mosbot-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
